const GITHUB_API = "https://api.github.com";

async function gh(
  path: string,
  options: RequestInit = {}
): Promise<unknown> {
  const token = Deno.env.get("GITHUB_TOKEN");
  if (!token) throw new Error("GITHUB_TOKEN não configurado");

  const res = await fetch(`${GITHUB_API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...(options.headers as Record<string, string>),
    },
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`GitHub API ${res.status} ${path}: ${err}`);
  }

  // 204 No Content
  if (res.status === 204) return null;
  return res.json();
}

async function getOwner(): Promise<string> {
  const user = (await gh("/user")) as { login: string };
  return user.login;
}

// ─── Tool registry ─────────────────────────────────────────────────────────

// Erros que valem retry automático (transientes)
function isRetryable(err: unknown): boolean {
  const msg = String(err);
  return (
    msg.includes("500") ||
    msg.includes("502") ||
    msg.includes("503") ||
    msg.includes("timeout") ||
    msg.includes("network")
  );
}

export async function executeTool(
  toolName: string,
  args: Record<string, unknown>,
  attempt = 0
): Promise<string> {
  try {
    return await _executeTool(toolName, args);
  } catch (err) {
    if (attempt < 2 && isRetryable(err)) {
      await new Promise((r) => setTimeout(r, 2_000 * (attempt + 1)));
      return executeTool(toolName, args, attempt + 1);
    }
    throw err;
  }
}

async function _executeTool(
  toolName: string,
  args: Record<string, unknown>
): Promise<string> {
  switch (toolName) {
    // ── GitHub: criar repositório ─────────────────────────────────────────
    case "github_create_repo": {
      const {
        name,
        description = "",
        private: isPrivate = true,
      } = args as { name: string; description?: string; private?: boolean };

      const owner = await getOwner();
      try {
        await gh(`/repos/${owner}/${name}`);
        return `Repositório já existia: https://github.com/${owner}/${name}\nOwner: ${owner}`;
      } catch (err) {
        if (!String(err).includes("404")) throw err;
      }

      await gh("/user/repos", {
        method: "POST",
        body: JSON.stringify({
          name,
          description,
          private: isPrivate,
          auto_init: true,
        }),
      });
      return `Repositório criado: https://github.com/${owner}/${name}\nOwner: ${owner}`;
    }

    // ── GitHub: commitar múltiplos arquivos via Trees API ─────────────────
    case "github_push_files": {
      const {
        repo,
        files,
        message = "feat: generated by AI squad",
        branch,
      } = args as {
        repo: string;
        files: { path: string; content: string }[];
        message?: string;
        branch?: string;
      };

      const owner = await getOwner();

      // Busca info do repo para pegar o default_branch real (pode ser master ou main)
      // Aguarda 2s para evitar race condition após github_create_repo
      await new Promise((r) => setTimeout(r, 2_000));
      const repoInfo = (await gh(`/repos/${owner}/${repo}`)) as {
        default_branch: string;
      };
      const targetBranch = branch ?? repoInfo.default_branch ?? "main";

      // 1. Tenta obter SHA do HEAD — com retry para race condition de auto_init
      let latestSha: string | null = null;
      let baseTreeSha: string | null = null;

      for (let attempt = 0; attempt < 3; attempt++) {
        try {
          const ref = (await gh(
            `/repos/${owner}/${repo}/git/refs/heads/${targetBranch}`
          )) as { object: { sha: string } };
          latestSha = ref.object.sha;
          const baseCommit = (await gh(
            `/repos/${owner}/${repo}/git/commits/${latestSha}`
          )) as { tree: { sha: string } };
          baseTreeSha = baseCommit.tree.sha;
          break;
        } catch (err) {
          const msg = String(err);
          if (msg.includes("404") && attempt < 2) {
            // repo pode estar ainda inicializando — aguarda e tenta de novo
            await new Promise((r) => setTimeout(r, 3_000));
            continue;
          }
          if (msg.includes("404")) {
            // repo genuinamente vazio (sem auto_init) — primeiro commit sem parent
            latestSha = null;
            baseTreeSha = null;
          } else {
            throw err;
          }
        }
      }

      // 2. Criar blobs para cada arquivo
      const treeItems = await Promise.all(
        files.map(async (f) => {
          const encoded = btoa(unescape(encodeURIComponent(f.content)));
          const blob = (await gh(`/repos/${owner}/${repo}/git/blobs`, {
            method: "POST",
            body: JSON.stringify({ content: encoded, encoding: "base64" }),
          })) as { sha: string };
          return { path: f.path, mode: "100644" as const, type: "blob" as const, sha: blob.sha };
        })
      );

      // 3. Nova tree
      const treeBody: Record<string, unknown> = { tree: treeItems };
      if (baseTreeSha) treeBody.base_tree = baseTreeSha;
      const tree = (await gh(`/repos/${owner}/${repo}/git/trees`, {
        method: "POST",
        body: JSON.stringify(treeBody),
      })) as { sha: string };

      // 4. Novo commit
      const commitBody: Record<string, unknown> = { message, tree: tree.sha };
      if (latestSha) commitBody.parents = [latestSha];
      const newCommit = (await gh(`/repos/${owner}/${repo}/git/commits`, {
        method: "POST",
        body: JSON.stringify(commitBody),
      })) as { sha: string };

      // 5. Criar ou atualizar ref
      if (latestSha) {
        // Branch existe — atualiza
        await gh(`/repos/${owner}/${repo}/git/refs/heads/${targetBranch}`, {
          method: "PATCH",
          body: JSON.stringify({ sha: newCommit.sha }),
        });
      } else {
        // Primeiro commit — cria o branch
        await gh(`/repos/${owner}/${repo}/git/refs`, {
          method: "POST",
          body: JSON.stringify({ ref: `refs/heads/${targetBranch}`, sha: newCommit.sha }),
        });
      }

      const fileList = files.map((f) => `  - ${f.path}`).join("\n");
      return `${files.length} arquivo(s) commitado(s) em https://github.com/${owner}/${repo} (branch: ${targetBranch})\n${fileList}`;
    }

    // ── GitHub: ler arquivo ───────────────────────────────────────────────
    case "github_read_file": {
      const { repo, path } = args as { repo: string; path: string };
      const owner = await getOwner();
      const file = (await gh(
        `/repos/${owner}/${repo}/contents/${path}`
      )) as { content: string };
      return atob(file.content.replace(/\n/g, ""));
    }

    // ── GitHub: aguardar resultado do Actions ─────────────────────────────
    case "github_get_actions_status": {
      const { repo, timeout_seconds = 120 } = args as {
        repo: string;
        timeout_seconds?: number;
      };
      const owner = await getOwner();

      // Aguarda o Actions registrar o run
      await new Promise((r) => setTimeout(r, 6_000));

      const runs = (await gh(
        `/repos/${owner}/${repo}/actions/runs?per_page=1`
      )) as { workflow_runs: { id: number; html_url: string }[] };

      if (!runs.workflow_runs?.length) {
        return "Nenhum Actions run encontrado. Verifique se há .github/workflows/ com um workflow válido.";
      }

      const { id: runId, html_url: runUrl } = runs.workflow_runs[0];

      // Poll até concluir
      const deadline = Date.now() + timeout_seconds * 1000;
      while (Date.now() < deadline) {
        const status = (await gh(
          `/repos/${owner}/${repo}/actions/runs/${runId}`
        )) as { status: string; conclusion: string };

        if (status.status === "completed") {
          const jobs = (await gh(
            `/repos/${owner}/${repo}/actions/runs/${runId}/jobs`
          )) as {
            jobs: { name: string; conclusion: string; steps: { name: string; conclusion: string }[] }[];
          };

          const summary = jobs.jobs
            .flatMap((j) =>
              j.steps.map(
                (s) =>
                  `${s.conclusion === "success" ? "✅" : s.conclusion === "failure" ? "❌" : "⏭️"} ${s.name}`
              )
            )
            .join("\n");

          return `Actions: ${status.conclusion.toUpperCase()}\nURL: ${runUrl}\n\n${summary}`;
        }

        await new Promise((r) => setTimeout(r, 15_000));
      }

      return `Actions ainda rodando após ${timeout_seconds}s. Acompanhe: ${runUrl}`;
    }

    // ── GitHub: logs detalhados do último run ─────────────────────────────
    case "github_get_actions_logs": {
      const { repo } = args as { repo: string };
      const owner = await getOwner();

      const runs = (await gh(
        `/repos/${owner}/${repo}/actions/runs?per_page=1`
      )) as { workflow_runs: { id: number }[] };

      if (!runs.workflow_runs?.length) return "Nenhum run encontrado.";

      const runId = runs.workflow_runs[0].id;
      const jobs = (await gh(
        `/repos/${owner}/${repo}/actions/runs/${runId}/jobs`
      )) as {
        jobs: {
          name: string;
          conclusion: string;
          steps: { name: string; conclusion: string; number: number }[];
        }[];
      };

      return jobs.jobs
        .map((j) => {
          const steps = j.steps
            .map((s) => `  [${s.conclusion ?? "pending"}] ${s.name}`)
            .join("\n");
          return `### ${j.name} (${j.conclusion ?? "running"})\n${steps}`;
        })
        .join("\n\n");
    }

    default:
      return `Tool '${toolName}' não implementada.`;
  }
}

// ─── OpenAI-compatible tool schema helpers ──────────────────────────────────

export const GITHUB_TOOLS = [
  {
    type: "function",
    function: {
      name: "github_create_repo",
      description: "Cria um novo repositório no GitHub",
      parameters: {
        type: "object",
        properties: {
          name: { type: "string", description: "Nome do repositório (sem espaços)" },
          description: { type: "string", description: "Descrição opcional" },
          private: { type: "boolean", description: "true para privado (padrão: true)" },
        },
        required: ["name"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "github_push_files",
      description: "Commita múltiplos arquivos no repositório de uma vez (usa Git Trees API para batch commit)",
      parameters: {
        type: "object",
        properties: {
          repo: { type: "string", description: "Nome do repositório" },
          files: {
            type: "array",
            items: {
              type: "object",
              properties: {
                path: { type: "string", description: "Caminho do arquivo, ex: src/index.ts" },
                content: { type: "string", description: "Conteúdo completo do arquivo" },
              },
              required: ["path", "content"],
            },
            description: "Lista de arquivos para commitar. Inclua SEMPRE .github/workflows/test.yml.",
          },
          message: { type: "string", description: "Mensagem de commit" },
          branch: { type: "string", description: "Branch de destino (padrão: main)" },
        },
        required: ["repo", "files"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "github_read_file",
      description: "Lê o conteúdo de um arquivo do repositório",
      parameters: {
        type: "object",
        properties: {
          repo: { type: "string" },
          path: { type: "string", description: "Caminho do arquivo no repo" },
        },
        required: ["repo", "path"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "github_get_actions_status",
      description: "Aguarda o GitHub Actions terminar e retorna o resultado dos testes. Faz polling automático.",
      parameters: {
        type: "object",
        properties: {
          repo: { type: "string", description: "Nome do repositório" },
          timeout_seconds: { type: "number", description: "Tempo máximo de espera em segundos (padrão: 120)" },
        },
        required: ["repo"],
      },
    },
  },
  {
    type: "function",
    function: {
      name: "github_get_actions_logs",
      description: "Retorna os logs detalhados do último Actions run (passos e conclusões de cada job)",
      parameters: {
        type: "object",
        properties: {
          repo: { type: "string" },
        },
        required: ["repo"],
      },
    },
  },
];
